carla:
    camera_width: 800
    camera_height: 640
    host: "127.0.0.1"
    port: 2000
    timeout: 5.0
    vehicle_model: "vehicle.audi.etron"
    pedestrian_model: "walker.pedestrian.0011"
    screen_height: 640
    screen_width: 800
    scaling_factor: 100.0
    max_deceleration: 200    # TODO: no idea how to get the right value.
    vis_trajectory_window_x: 800
    vis_trajectory_window_y: 480
    vis_point_radius: 6
    vis_scaling_factor_x: 4
    vis_scaling_factor_y: 20
yolo:
    device: "cuda:0"
    data: "weights/coco.yaml"
    weights: "weights/yolov5m.pt"
    half: false
    img_size: 640
    conf_thres: 0.55
    iou_thres: 0.5
    max_det: 1000
cm:     # Connected Mobility.
    max_time_diff: 1.0
    max_range_vehicle: 55
    max_range_pedestrian: 25
