carla:
    vehicle_cam_width: 800
    vehicle_cam_height: 640
    pedestrian_cam_width: 800
    pedestrian_cam_height: 400
    host: "127.0.0.1"
    port: 2000
    timeout: 5.0
    vehicle_model: "vehicle.audi.etron"
    pedestrian_model: "walker.pedestrian.0011"
    screen_height: 1080
    screen_width: 800
    scaling_factor: 100.0
    max_deceleration: 200    # TODO: no idea how to get the right value.
    vis_line_width: 3
    vis_trajectory_window_x: 1040
    vis_trajectory_window_y: 480
    vis_point_radius: 6
    vis_scaling_factor_x: 4
    vis_scaling_factor_y: 20
    vis_sending_range: 2
yolo:
    device: "cuda:0"
    data: "weights/coco.yaml"
    weights: "weights/yolov5m.pt"
    half: false
    img_size: 640
    conf_thres: 0.7
    iou_thres: 0.5
    max_det: 1000
    x_diff: 100
    y_diff: 370
cm:     # Connected Mobility.
    deceleration_threshold: 0.005
    max_time_diff: 1.0
    max_range_vehicle: 55
    max_range_pedestrian: 25
